# Generated by Django 4.2 on 2023-05-03 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_num', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')])),
                ('holder_name', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]{3}$')])),
                ('valid_month', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{2}$')])),
                ('valid_year', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{2}$')])),
                ('mobile', models.CharField(default=0, max_length=11)),
                ('email', models.CharField(default=0, max_length=30)),
                ('image', models.ImageField(default='temp.jpeg', upload_to=None)),
            ],
        ),
    ]
