# Generated by Django 4.2 on 2023-05-12 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='valid_year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$')]),
        ),
    ]
